### ISSUE TITLE
Not working on IE10 and IE11

### ISSUE THREAD

**Issue by ghostbar** [ghostbar/angular-zxcvbn#16]
From #15:

@ghostbar / @jamesclark92: as you can see from the travis/saucelabs output few tests are not properly working on IE10/IE11 so there showuld be a probably bug affecting them:

https://travis-ci.org/evilaliv3/angular-zxcvbn/jobs/116266856
https://api.travis-ci.org/jobs/116266856/log.txt?deansi=true

the logs anyhow git you a precise idea of what is failing and affectes IE10 and IE11 exactly on the same 4 tests:

```
IE 11.0.0 (Windows 10 0.0.0) zxcvbn attribute directive with extras attribute with form object should only pass non-null extras variables FAILED
    Expected '{"password":"password","score":2}' to equal '{"password":"password","extras":["[object Object]"],"score":2}'.
       at Anonymous function (/home/travis/build/evilaliv3/angular-zxcvbn/test/attribute-tests.js:115:7)

IE 11.0.0 (Windows 10 0.0.0) zxcvbn attribute directive with extras attribute with form object should detect a form field change and make another call to zxcvbn with the updated value FAILED
    Expected spy zxcvbn to have been called with [ 'password', [ 'test@example.com', 'jonskeet' ] ] but actual calls were [ 'password' ].
       at Anonymous function (/home/travis/build/evilaliv3/angular-zxcvbn/test/attribute-tests.js:129:7)
    Expected spy zxcvbn to have been called with [ 'password', [ 'test@example.com', 'chucknorris' ] ] but actual calls were [ 'password' ].
       at Anonymous function (/home/travis/build/evilaliv3/angular-zxcvbn/test/attribute-tests.js:134:7)

IE 11.0.0 (Windows 10 0.0.0) zxcvbn attribute directive with extras attribute with form object should detect when a form field has been added and recall zxcvbn with the added field too FAILED
    Expected spy zxcvbn to have been called with [ 'password', [ 'test@example.com', 'john_skeet' ] ] but actual calls were [ 'password' ].
       at Anonymous function (/home/travis/build/evilaliv3/angular-zxcvbn/test/attribute-tests.js:149:7)
    Expected spy zxcvbn to have been called with [ 'password', [ 'test@example.com', 'john_skeet', 'chucknorris' ] ] but actual calls were [ 'password' ].
       at Anonymous function (/home/travis/build/evilaliv3/angular-zxcvbn/test/attribute-tests.js:155:7)

IE 11.0.0 (Windows 10 0.0.0) zxcvbn attribute directive with extras attribute with form object should detect when a form field has been removed and recall zxcvbn without that field FAILED
    Expected spy zxcvbn to have been called with [ 'password', [ 'test@example.com', 'john_skeet', 'chucknorris' ] ] but actual calls were [ 'password' ].
       at Anonymous function (/home/travis/build/evilaliv3/angular-zxcvbn/test/attribute-tests.js:170:7)
    Expected spy zxcvbn to have been called with [ 'password', [ 'test@example.com', 'john_skeet' ] ] but actual calls were [ 'password' ].
       at Anonymous function (/home/travis/build/evilaliv3/angular-zxcvbn/test/attribute-tests.js:176:7)
```

**Comment by evilaliv3** [comment]
in https://github.com/evilaliv3/angular-zxcvbn/tree/fix/16 i've started investigating the issue.

i've reasons to think that the bug lies here:
https://github.com/ghostbar/angular-zxcvbn/blob/master/src/attribute-directive.js#L55
```
55            if (angular.isDefined(extras)) {
56              if (angular.isArray(extras)) {
57                scope.zxArrayWatcher();
58              } else if (scope.isForm(extras)) {
59                scope.zxFormWatcher();
60              }
61            }
```
